server:
  port: 8080
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./enm_dev;MODE=MYSQL
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console